language: go

go:
  - 1.7.x

install:
  - mkdir $GOPATH/bin
  - curl https://glide.sh/get | sh
  - glide install

script: go test -v $(glide nv)

before_deploy:
  - go get github.com/mitchellh/gox
  - gox -output "release/{{.OS}}_{{.Arch}}_${TRAVIS_TAG}/{{.Dir}}" -ldflags "-X main.Version=${TRAVIS_TAG}" ./cmd/mdq/
  - cd release
  - for file in $(find ./*/* -type f); do zip $(basename $(dirname $file)).zip $file; done

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "*.zip"
  overwrite: true
  on:
    tags: true
